agent_name = "ginger-voice-bot"
image = "pierretokns/ginger:1"
secret_set = "ginger-secrets"
agent_profile = "agent-1x"

# RECOMMENDED: Set an image pull secret:
# https://docs.pipecat.ai/deployment/pipecat-cloud/fundamentals/secrets#image-pull-secrets
# image_credentials = "your_image_pull_secret"

[scaling]
	min_agents = 1
	max_agents = 1
